---
apiVersion: v1
kind: Service
metadata:
  name: main
  labels:
    app: main
spec:
  ports:
  - name: http
    port: 3001
    protocol: TCP
    targetPort: 3000
  selector:
    app: main
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: appointment-services
  labels:
    app: appointment-services
spec:
  ports:
  - name: http
    port: 3002
    protocol: TCP
    targetPort: 3000
  selector:
    app: appointment-services
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: authentication-services
  labels:
    app: authentication-services
spec:
  ports:
  - name: http
    port: 3003
    protocol: TCP
    targetPort: 3000
  selector:
    app: authentication-services
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: chat-services
  labels:
    app: chat-services
spec:
  ports:
  - name: http
    port: 3004
    protocol: TCP
    targetPort: 3000
  selector:
    app: chat-services
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: ai-ml-analytics-python
  labels:
    app: ai-ml-analytics-python
spec:
  ports:
  - name: http
    port: 3005
    protocol: TCP
    targetPort: 3000
  selector:
    app: ai-ml-analytics-python
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: notification-services-ms
  labels:
    app: notification-services-ms
spec:
  ports:
  - name: http
    port: 3006
    protocol: TCP
    targetPort: 3000
  selector:
    app: notification-services-ms
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: patient-services-ms
  labels:
    app: patient-services-ms
spec:
  ports:
  - name: http
    port: 3007
    protocol: TCP
    targetPort: 3000
  selector:
    app: patient-services-ms
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: physician-management-ui-ux
  labels:
    app: physician-management-ui-ux
spec:
  ports:
  - name: http
    port: 3008
    protocol: TCP
    targetPort: 3000
  selector:
    app: physician-management-ui-ux
  type: LoadBalancer