---
apiVersion: v1
kind: Service
metadata:
  name: main
  labels:
    app: main
spec:
  ports:
  - name: http
    port: 3001
    protocol: TCP
    targetPort: 3000
  selector:
    app: main
  type: LoadBalancer
---
